services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sistema_reservas_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - mongodb
    environment:
      - PYTHONUNBUFFERED=1

  mongodb:
    image: mongo:latest
    container_name: sistema_reservas_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
